name: ChatPlugin
version: @version@
main: net.deltapvp.chatplugin.ChatPlugin
authors: [ powercas_gamer ]
depend: [PlaceholderAPI]
commands:
  chatplugin:
    usage: /<command>
    description: reload the plugin

permissions:
  chatplugin.color:
    default: op
    description: allows you to use chatcolors and RGB in chat.
  chatplugin.use:
    default: op
    description: permission to use the thing
